#!/bin/csh
set name=qtl
set program=`which $name`
set xoptions="-sb -sl 1000 +j +mb -si -sk -title $name"
set fontsize="-fn terminal -fg black -bg lightGrey -geometry 80x54+35+25"

echo "Running $name in xterm..."
if (-e /usr/openwin/bin/xterm) then
	exec /usr/openwin/bin/xterm  $xoptions $fontsize -e $program $*
else if (-e /usr/openwin/demo/xterm) then
	exec /usr/openwin/demo/xterm $xoptions $fontsize -e $program $*
else
	exec xterm $options $fontsize -e $program
endif
